name: Deploy to Sakura VPS (rsync over SSH)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # SSH鍵とホスト鍵をセットアップ（Secrets を使う）
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # rsync で配備（不要物は除外 / サーバ側の余計なファイルは --delete で除去）
      - name: Deploy via rsync
        run: |
          rsync -avzr --delete \
            --exclude='.git*' --exclude='.github/' --exclude='README*' --exclude='LICENSE*' \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}
